### ISSUE TITLE
List Sort

### ISSUE THREAD

**Issue by jpleite** [madmachinations/home-assistant-todoist-shopping-list#6]
Thanks for your custom integration @madmachinations . Just a question: the list is integrated like a local todo list without the possibility to sort like you do in HA Shopping lists. Any way to solve this?

**Comment by madmachinations** [comment]
The sorting won't work in HA I'm afraid, it will always get overwritten.

It gets the list of items from Todoist, in the order in which Todoist provides them.

It then replaces the entire contents of the HA shopping list with that data.

If you sorted the list in Todoist, it might change the order in which they appear in HA? But I'm not sure about that tbh.

I'm also not sure if changing the order in the Alexa app will change the order in Todoist.

**Comment by jpleite** [comment]
thanks @madmachinations Either changing the order in todoist or Alexa changes the order in HA. I guess HA will eventually implement sorting in local lists

**Comment by madmachinations** [comment]
HA does have sorting, but this component ignores it and just replaces the entire list whenever it refreshes. So any changes made to the order in HA just get forgotten.

I will keep this issue open as something to consider adding though next time I have my hands in it :)

**Comment by madmachinations** [comment]
As part of the big re-factor after the API closure  (#7) - I don't think this will be possible. The order will be whatever it is unfortunately.

I would like to say I will re-visit this if it becomes possible, but I doubt it will considering Amazon shutting down access to the list API and such. So I can't see it getting any better in the future.

But if it does, it can be looked at then.
