### ISSUE TITLE
I can't follow the installation instructions

### ISSUE THREAD

**Issue by simonotter** [madmachinations/home-assistant-todoist-shopping-list#8]
Hi there,
I can't follow the installation instructions. 

`copy the todoist_shopping_list folder to your custom_components directory inside your Home Assistant config folder.`

When I visit the share for the Home Assistant config folder, there is no todoist_shopping_list folder available to copy into the custom_components directory.

Any help would be really appreciated. Thanks.

Here's a screenshot showing the Alexa Shopping List is available in Home Assistant (if this helps).
![image](https://github.com/user-attachments/assets/1bff02d6-984c-405d-b208-b7cdb31a7744)

**Comment by madmachinations** [comment]
I'm not sure what you've done here tbh.

The instruction is saying that within your home assistant config folder - there should be a folder called "custom_components". And if that doesn't exist, then you should create it. This is where you can dump all kinds of custom components for HA to load and use.

When you have your custom_components folder, you would then unzip the files you downloaded from here, and copy the "todoist_shopping_list" folder from there, into your custom_components folder. That is essentially "installing" the component, which HA would see after it had been restarted.

HOWEVER - This is all pointless at this moment in time I'm afraid. This component is not working right now.

Amazon closed the API that allowed other platforms to access the data on your alexa shopping list, about 2 months ago.

There is a solution, which I am currently building. It will be up sometime this week if all goes well over the next 2 days.

Updates about this are being posted in the "API list closure" issue ( #7 ). I will post in there when it is released and ready for use. With it will come new installation instructions, as much more is required of the new version.
